## <font color="royalblue">**Extracción de datos**</font>
### <font color="royalblue">**Reconstrucción de descripción Adzuna**</font>
Las descripciones extraidas a traves de API Adzuna estaban truncadas a 5000 caracteres.  
Por tal motivo se intenta recuperar con la url de la oferta las descripciones completas.  
- Se aplico la función *obtener_descripcion_completa(url)* al dataframe df_Adzuna.  
- Para salvaguardar las descripciones completas originales obtenidas se exportan al archivo *'df_Adzuna_v1_descripcion_completa.csv'*, esto debido a la constante actualizacion de la web de Adzuna donde entran y salen regularmente ofertas de empleo.  
- Se obtienen 51 descripciones, 25 paginas no encontradas.
- Respecto a las 25 no encontradas seran conpmetadas con las descripciones trucadas.
-  Se creo la función *filtrar_descripcion*, para extraer del Web Scraping las descripciones activas, ausentes e inactivas.
- Adicionalmente se realizo una revisión de las diferencias entre las descripciones.
- Los datos fueron exportados en archivo .csv, para posterior preprocesamiento.

In [ ]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
import requests
from bs4 import BeautifulSoup

In [ ]:
# Importar los dataframes de Adzuna
df_Adzuna=pd.read_csv('df_Adzuna.csv')
df_Adzuna_desc=pd.read_csv('df_Adzuna_v1_descripcion_completa.csv')

In [ ]:
# Renombrar las columnas a español
df_Adzuna.rename(columns={'title': 'titulo', 'description': 'descripcion', 'location': 'ubicacion', 'company': 'empresa', 'date': 'fecha', 'url_': 'url'}, inplace=True)

In [ ]:
# Funcion que permite obtener la descripcion completa de una oferta laboral
def obtener_descripcion_completa(url):
    """Funcion que permite obtener la descripcion completa de una oferta laboral a partir de su url"""
    try:
        response = requests.get(url, timeout=10)
        soup = BeautifulSoup(response.text, "html.parser")

        # Así que buscamos el texto principal de la oferta
        texto = soup.get_text(separator=" ", strip=True)

        return texto
    except:
        return None

# /html/body/div[1]/main/div/section[2]/div[1]/section

In [ ]:
# Aplicar funcion para obtener la descripcion completa por Web Scraping
df_Adzuna["descripcion_completa"] = df_Adzuna["url"].apply(obtener_descripcion_completa)

In [6]:
# Exportar el dataframe con la descripcion completa 
#df_Adzuna.to_csv("df_Adzuna_v1_descripcion_completa.csv", index=False)

# Cargar el dataframe con la descripcion completa para su posterior analisis y limpieza
df_Adzuna_desc=pd.read_csv('df_Adzuna_v1_descripcion_completa.csv')

In [7]:
def duplicadas(df, columna):
    """Funcion que permite identificar las filas duplicadas en una columna específica de un DataFrame"""
    duplicadas = df[df.duplicated(subset=[columna], keep=False)]
    print(f"\n Filas duplicadas en la columna '{columna}': {len(duplicadas)}")
    return duplicadas

In [8]:
duplicadas(df_Adzuna_desc, "descripcion_completa")

 Filas duplicadas en la columna 'descripcion_completa': 25

,titulo,empresa,ubicacion,modalidad,tipo_contrato,contract_type,experiencia_años,experiencia_nivel,nivel_educativo,hard_skills,...,idiomas,fecha,contrac_time,category,descripcion,portal_web,id,url,contrato,descripcion_completa
5,Senior Data Analyst,Smadex SLU,Barcelona,NaN,NaN,NaN,NaN,senior,NaN,NaN,...,NaN,2025-11-24T18:38:14Z,NaN,NaN,Smadex is a leading advertising technology com...,Adzuna,5511391610,https://www.adzuna.es/details/5511391610?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
6,Senior Data Analyst,Zynga,Barcelona,NaN,NaN,NaN,NaN,senior,NaN,NaN,...,NaN,2026-03-05T20:55:19Z,NaN,NaN,"Level Up Your Career with Zynga! At Zynga, we ...",Adzuna,5655182942,https://www.adzuna.es/details/5655182942?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
11,Marketing Data Analyst,Proton,Barcelona,NaN,NaN,NaN,NaN,becario,NaN,NaN,...,NaN,2026-03-05T20:55:01Z,NaN,NaN,Join Proton and build a better internet where ...,Adzuna,5655180976,https://www.adzuna.es/details/5655180976?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
12,Marketing Data Analyst,Proton Ag,Barcelona,NaN,NaN,NaN,NaN,becario,NaN,NaN,...,NaN,2026-03-05T20:55:17Z,NaN,NaN,Join Proton and build a better internet where ...,Adzuna,5655182688,https://www.adzuna.es/details/5655182688?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
13,Marketing Data Analyst,Proton Ag,Barcelona,NaN,NaN,NaN,NaN,becario,NaN,NaN,...,NaN,2026-03-05T20:54:54Z,NaN,NaN,Join Proton and build a better internet where ...,Adzuna,5655180333,https://www.adzuna.es/details/5655180333?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
14,Data Analyst & Reporting Services,Randstad ES,Barcelona,NaN,formación,permanent,80.0,NaN,NaN,NaN,...,NaN,2026-02-21T02:43:29Z,NaN,Trabajos en informática,Data Analyst & Reporting Services ¿Tienes expe...,Adzuna,5639115990,https://www.adzuna.es/details/5639115990?utm_m...,"permanent, formación",Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
15,Senior HR Data Analyst,"UL, LLC",Barcelona,híbrido,NaN,NaN,NaN,senior,NaN,NaN,...,NaN,2026-02-12T05:02:31Z,NaN,NaN,We are currently looking for a Senior HR Data ...,Adzuna,5625658757,https://www.adzuna.es/details/5625658757?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
18,Data Analyst Para Banca,Banco Mediolanum,Barcelona,NaN,NaN,NaN,NaN,becario,NaN,NaN,...,NaN,2026-03-07T20:56:37Z,NaN,NaN,¿Te gustaría desarrollar tu carrera en el sect...,Adzuna,5657840099,https://www.adzuna.es/details/5657840099?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
19,Data Analyst Senior Ecommerce & App,Elabs Consulting,Barcelona,NaN,NaN,NaN,NaN,senior,NaN,git,...,NaN,2026-03-05T20:55:39Z,NaN,NaN,"Sobre el puestoEn Elabs Consulting, agencia de...",Adzuna,5655184982,https://www.adzuna.es/details/5655184982?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
20,Marketing Data Analyst- Monopoly Go!,Scopely,Barcelona,híbrido,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2026-03-06T20:55:36Z,NaN,NaN,Scopely is looking for a Marketing Data Analys...,Adzuna,5656541727,https://www.adzuna.es/details/5656541727?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
21,"Principal Data Analyst Barcelona, Spain",Zynga,Barcelona,NaN,NaN,NaN,NaN,senior,NaN,NaN,...,NaN,2026-03-06T20:55:51Z,NaN,NaN,"At Zynga, we bring people together through the...",Adzuna,5656543416,https://www.adzuna.es/details/5656543416?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
22,"Principal Data Analyst Barcelona, Spain",Zynga,Barcelona,NaN,NaN,NaN,NaN,senior,NaN,NaN,...,NaN,2026-03-07T20:56:24Z,NaN,NaN,"At Zynga, we bring people together through the...",Adzuna,5657839002,https://www.adzuna.es/details/5657839002?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
24,SAP Financial Reporting Data Analyst,Michael Page,Barcelona,NaN,NaN,permanent,NaN,NaN,NaN,NaN,...,NaN,2026-02-17T02:34:31Z,NaN,Trabajos en informática,SAP Financial Reporting Data Analyst Perfil bu...,Adzuna,5632520842,https://www.adzuna.es/details/5632520842?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
29,Data Analyst It (Sector Banca),Banco Mediolanum,Barcelona,NaN,NaN,NaN,NaN,becario,NaN,NaN,...,NaN,2026-03-06T20:55:46Z,NaN,NaN,¿Te gustaría desarrollar tu carrera en el sect...,Adzuna,5656542793,https://www.adzuna.es/details/5656542793?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
32,Senior Data Analyst - Yahtzee! With Buddies,Scopely,Barcelona,híbrido,NaN,NaN,NaN,senior,NaN,NaN,...,NaN,2026-03-05T20:55:01Z,NaN,NaN,Scopely is looking for a Sr. Data Analyst to j...,Adzuna,5655180991,https://www.adzuna.es/details/5655180991?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
33,Remote: Online Data Analyst - Spanish (Es),TELUS Digital,Barcelona,NaN,freelance,NaN,NaN,NaN,NaN,git,...,NaN,2026-03-07T20:57:07Z,NaN,NaN,Are you a detail-oriented individual with a pa...,Adzuna,5657842573,https://www.adzuna.es/details/5657842573?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
34,Remote: Online Data Analyst - Spanish (Es),TELUS Digital,Barcelona,NaN,freelance,NaN,NaN,NaN,NaN,git,...,NaN,2026-03-06T20:55:50Z,NaN,NaN,Are you a detail-oriented individual with a pa...,Adzuna,5656543296,https://www.adzuna.es/details/5656543296?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
36,"Data Analyst Intern, Performance Media EMEA",Criteo Technology,Barcelona,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2025-12-03T20:05:44Z,NaN,NaN,What You'll Do: As a member of our Performance...,Adzuna,5526420444,https://www.adzuna.es/details/5526420444?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
47,Business Analyst (Data / SQL / Seguros),Krell Consulting & Training,Barcelona,NaN,NaN,permanent,NaN,senior,NaN,sql,...,NaN,2026-02-04T02:21:00Z,NaN,Trabajos en informática,Business Analyst (Data / SQL / Seguros) Descri...,Adzuna,5612708407,https://www.adzuna.es/details/5612708407?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
49,Principal Marketing Analyst,Zynga,Barcelona,NaN,NaN,NaN,NaN,senior,NaN,NaN,...,NaN,2026-03-06T20:55:50Z,NaN,NaN,Join to apply for the Principal Data Analyst r...,Adzuna,5656543345,https://www.adzuna.es/details/5656543345?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
53,Analytics Manager,Socialpoint,Barcelona,NaN,NaN,NaN,NaN,senior,NaN,NaN,...,NaN,2026-03-06T20:55:51Z,NaN,NaN,Join to apply for the Principal Data Analyst r...,Adzuna,5656543375,https://www.adzuna.es/details/5656543375?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
56,IT Anaplan Consultant,Michael Page,Barcelona,NaN,formación,permanent,NaN,NaN,NaN,NaN,...,NaN,2026-02-17T02:34:31Z,NaN,Trabajos en informática,IT Anaplan Consultant Perfil buscado (Hombre/M...,Adzuna,5632520849,https://www.adzuna.es/details/5632520849?utm_m...,"permanent, formación",Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
65,Head Of Content (Personal Brand Growth & Conte...,Soft Landing Agency,Barcelona,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2026-03-05T20:54:48Z,NaN,NaN,En Landing construimos motores de crecimiento ...,Adzuna,5655179685,https://www.adzuna.es/details/5655179685?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
66,Head Of Content (Personal Brand Growth & Conte...,Soft Landing Agency,Barcelona,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2026-03-07T20:57:00Z,NaN,NaN,En Landing construimos motores de crecimiento ...,Adzuna,5657842068,https://www.adzuna.es/details/5657842068?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...
75,Demand Generation Analyst (Temporary Contract),SAP,Barcelona,NaN,temporal,NaN,NaN,NaN,NaN,NaN,...,NaN,2026-03-06T20:55:36Z,NaN,NaN,Demand Generation Analyst (Temporary Contract)...,Adzuna,5656541670,https://www.adzuna.es/details/5656541670?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...

In [11]:
def filtrar_descripcion(texto):
    """Funcion que permite filtrar la descripcion completa de una oferta laboral de Adzuna para obtener solo la parte relevante"""
    oferta_activa = "Inscribirse en esta oferta"
    oferta_ausente = "Página no encontrada"
    oferta_inactiva = "Lo sentimos, este empleo ya no está disponible"

    if oferta_activa in texto:
        descripcion = texto.split(oferta_activa)[1].strip()
        return descripcion
    elif oferta_ausente in texto:
        return None
    elif oferta_inactiva in texto:
        descripcion_no_disponible = texto.split(oferta_inactiva)[1].strip()
        descripcion_completa = descripcion_no_disponible.split("Trabajos populares")[0].strip()
        return descripcion_completa
    else:
        return texto

In [12]:
df_Adzuna_desc["descripcion_filtrada"] = df_Adzuna_desc["descripcion_completa"].apply(filtrar_descripcion)
df_Adzuna_desc["es_truncada"] = df_Adzuna_desc["descripcion_filtrada"].isna()
df_Adzuna_desc

,titulo,empresa,ubicacion,modalidad,tipo_contrato,contract_type,experiencia_años,experiencia_nivel,nivel_educativo,hard_skills,...,contrac_time,category,descripcion,portal_web,id,url,contrato,descripcion_completa,descripcion_filtrada,es_truncada
0,Data Analyst,Perk,Barcelona,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,About Us Perk (formerly TravelPerk) is the int...,Adzuna,5655420542,https://www.adzuna.es/details/5655420542?utm_m...,NaN,Data Analyst Empleos en Barcelona ¿Qué? ¿Dónde...,About Us Perk (formerly TravelPerk) is the int...,False
1,Data Analyst,Veepee,Barcelona,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Pioneer of online flash sales since 2001 and k...,Adzuna,5590818342,https://www.adzuna.es/details/5590818342?utm_m...,NaN,Data Analyst Empleos en Barcelona ¿Qué? ¿Dónde...,Pioneer of online flash sales since 2001 and k...,False
2,Data Analyst,Propelling Tech,Barcelona,NaN,NaN,NaN,NaN,senior,NaN,NaN,...,NaN,NaN,"As a Data Analyst , you will be part of a high...",Adzuna,5584544401,https://www.adzuna.es/details/5584544401?utm_m...,NaN,Data Analyst Empleos en Barcelona ¿Qué? ¿Dónde...,"As a Data Analyst , you will be part of a high...",False
3,Data Analyst,PrimeIT,Barcelona,NaN,NaN,NaN,3.0,NaN,NaN,"python, sql, power bi, tableau",...,NaN,NaN,Qué buscamos? A partir de 3 años de experienci...,Adzuna,5304781614,https://www.adzuna.es/details/5304781614?utm_m...,NaN,Data Analyst Empleos en Barcelona ¿Qué? ¿Dónde...,Qué buscamos? A partir de 3 años de experienc...,False
4,Data Analyst Jr,Solicitud de empleo para Data Analyst Jr en DD...,Barcelona,NaN,NaN,NaN,NaN,junior,NaN,git,...,NaN,NaN,"Perfil Si te apasionan los datos, quieres apre...",Adzuna,5556867176,https://www.adzuna.es/details/5556867176?utm_m...,NaN,Data Analyst Jr Empleos en Barcelona ¿Qué? ¿Dó...,"Perfil Si te apasionan los datos, quieres apre...",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,Senior Finance Systems Project Manager - HQ,Glovo,Barcelona,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Job Description YOUR MISSION To be a Project M...,Adzuna,5648038417,https://www.adzuna.es/details/5648038417?utm_m...,NaN,Senior Finance Systems Project Manager - HQ Em...,Senior Finance Systems Project Manager - HQ Ub...,False
72,HQ BARCELONA - Senior Python Developer (Data T...,Jobandtalent,Barcelona,NaN,NaN,NaN,NaN,NaN,NaN,git,...,NaN,Trabajos en informática,Who we are : We are a workforce on-demand comp...,Adzuna,4800600477,https://www.adzuna.es/details/4800600477?utm_m...,NaN,HQ BARCELONA - Senior Python Developer (Data T...,Who we are: We are a workforce on-demand compa...,False
73,Analista de Producto,Product Madness,Barcelona,NaN,NaN,NaN,NaN,NaN,grado,NaN,...,NaN,NaN,Estamos ampliando nuestros equipos y esta es u...,Adzuna,5548465130,https://www.adzuna.es/details/5548465130?utm_m...,NaN,Analista de Producto Empleos en Barcelona ¿Qué...,Estamos ampliando nuestros equipos y esta es u...,False
74,Senior Data Architect,Bunge,Barcelona,NaN,NaN,NaN,NaN,senior,NaN,NaN,...,NaN,NaN,Location : Barcelona Hub City : Barcelona Stat...,Adzuna,5314694773,https://www.adzuna.es/details/5314694773?utm_m...,NaN,Senior Data Architect Empleos en Barcelona ¿Qu...,Location : Barcelona Hub City : Barcelona Stat...,False
75,Demand Generation Analyst (Temporary Contract),SAP,Barcelona,NaN,temporal,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Demand Generation Analyst (Temporary Contract)...,Adzuna,5656541670,https://www.adzuna.es/details/5656541670?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...,None,True

In [13]:
df_Adzuna_desc["descripcion_final"]=df_Adzuna_desc["descripcion_filtrada"].fillna(df_Adzuna_desc["descripcion"])
df_Adzuna_desc

,titulo,empresa,ubicacion,modalidad,tipo_contrato,contract_type,experiencia_años,experiencia_nivel,nivel_educativo,hard_skills,...,category,descripcion,portal_web,id,url,contrato,descripcion_completa,descripcion_filtrada,es_truncada,descripcion_final
0,Data Analyst,Perk,Barcelona,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,About Us Perk (formerly TravelPerk) is the int...,Adzuna,5655420542,https://www.adzuna.es/details/5655420542?utm_m...,NaN,Data Analyst Empleos en Barcelona ¿Qué? ¿Dónde...,About Us Perk (formerly TravelPerk) is the int...,False,About Us Perk (formerly TravelPerk) is the int...
1,Data Analyst,Veepee,Barcelona,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Pioneer of online flash sales since 2001 and k...,Adzuna,5590818342,https://www.adzuna.es/details/5590818342?utm_m...,NaN,Data Analyst Empleos en Barcelona ¿Qué? ¿Dónde...,Pioneer of online flash sales since 2001 and k...,False,Pioneer of online flash sales since 2001 and k...
2,Data Analyst,Propelling Tech,Barcelona,NaN,NaN,NaN,NaN,senior,NaN,NaN,...,NaN,"As a Data Analyst , you will be part of a high...",Adzuna,5584544401,https://www.adzuna.es/details/5584544401?utm_m...,NaN,Data Analyst Empleos en Barcelona ¿Qué? ¿Dónde...,"As a Data Analyst , you will be part of a high...",False,"As a Data Analyst , you will be part of a high..."
3,Data Analyst,PrimeIT,Barcelona,NaN,NaN,NaN,3.0,NaN,NaN,"python, sql, power bi, tableau",...,NaN,Qué buscamos? A partir de 3 años de experienci...,Adzuna,5304781614,https://www.adzuna.es/details/5304781614?utm_m...,NaN,Data Analyst Empleos en Barcelona ¿Qué? ¿Dónde...,Qué buscamos? A partir de 3 años de experienc...,False,Qué buscamos? A partir de 3 años de experienc...
4,Data Analyst Jr,Solicitud de empleo para Data Analyst Jr en DD...,Barcelona,NaN,NaN,NaN,NaN,junior,NaN,git,...,NaN,"Perfil Si te apasionan los datos, quieres apre...",Adzuna,5556867176,https://www.adzuna.es/details/5556867176?utm_m...,NaN,Data Analyst Jr Empleos en Barcelona ¿Qué? ¿Dó...,"Perfil Si te apasionan los datos, quieres apre...",False,"Perfil Si te apasionan los datos, quieres apre..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,Senior Finance Systems Project Manager - HQ,Glovo,Barcelona,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Job Description YOUR MISSION To be a Project M...,Adzuna,5648038417,https://www.adzuna.es/details/5648038417?utm_m...,NaN,Senior Finance Systems Project Manager - HQ Em...,Senior Finance Systems Project Manager - HQ Ub...,False,Senior Finance Systems Project Manager - HQ Ub...
72,HQ BARCELONA - Senior Python Developer (Data T...,Jobandtalent,Barcelona,NaN,NaN,NaN,NaN,NaN,NaN,git,...,Trabajos en informática,Who we are : We are a workforce on-demand comp...,Adzuna,4800600477,https://www.adzuna.es/details/4800600477?utm_m...,NaN,HQ BARCELONA - Senior Python Developer (Data T...,Who we are: We are a workforce on-demand compa...,False,Who we are: We are a workforce on-demand compa...
73,Analista de Producto,Product Madness,Barcelona,NaN,NaN,NaN,NaN,NaN,grado,NaN,...,NaN,Estamos ampliando nuestros equipos y esta es u...,Adzuna,5548465130,https://www.adzuna.es/details/5548465130?utm_m...,NaN,Analista de Producto Empleos en Barcelona ¿Qué...,Estamos ampliando nuestros equipos y esta es u...,False,Estamos ampliando nuestros equipos y esta es u...
74,Senior Data Architect,Bunge,Barcelona,NaN,NaN,NaN,NaN,senior,NaN,NaN,...,NaN,Location : Barcelona Hub City : Barcelona Stat...,Adzuna,5314694773,https://www.adzuna.es/details/5314694773?utm_m...,NaN,Senior Data Architect Empleos en Barcelona ¿Qu...,Location : Barcelona Hub City : Barcelona Stat...,False,Location : Barcelona Hub City : Barcelona Stat...
75,Demand Generation Analyst (Temporary Contract),SAP,Barcelona,NaN,temporal,NaN,NaN,NaN,NaN,NaN,...,NaN,Demand Generation Analyst (Temporary Contract)...,Adzuna,5656541670,https://www.adzuna.es/details/5656541670?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...,None,True,Demand Generation Analyst (Temporary Contract)...

In [14]:
duplicadas(df_Adzuna_desc, "descripcion_final")

 Filas duplicadas en la columna 'descripcion_final': 5

,titulo,empresa,ubicacion,modalidad,tipo_contrato,contract_type,experiencia_años,experiencia_nivel,nivel_educativo,hard_skills,...,category,descripcion,portal_web,id,url,contrato,descripcion_completa,descripcion_filtrada,es_truncada,descripcion_final
11,Marketing Data Analyst,Proton,Barcelona,NaN,NaN,NaN,NaN,becario,NaN,NaN,...,NaN,Join Proton and build a better internet where ...,Adzuna,5655180976,https://www.adzuna.es/details/5655180976?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...,None,True,Join Proton and build a better internet where ...
12,Marketing Data Analyst,Proton Ag,Barcelona,NaN,NaN,NaN,NaN,becario,NaN,NaN,...,NaN,Join Proton and build a better internet where ...,Adzuna,5655182688,https://www.adzuna.es/details/5655182688?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...,None,True,Join Proton and build a better internet where ...
13,Marketing Data Analyst,Proton Ag,Barcelona,NaN,NaN,NaN,NaN,becario,NaN,NaN,...,NaN,Join Proton and build a better internet where ...,Adzuna,5655180333,https://www.adzuna.es/details/5655180333?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...,None,True,Join Proton and build a better internet where ...
21,"Principal Data Analyst Barcelona, Spain",Zynga,Barcelona,NaN,NaN,NaN,NaN,senior,NaN,NaN,...,NaN,"At Zynga, we bring people together through the...",Adzuna,5656543416,https://www.adzuna.es/details/5656543416?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...,None,True,"At Zynga, we bring people together through the..."
22,"Principal Data Analyst Barcelona, Spain",Zynga,Barcelona,NaN,NaN,NaN,NaN,senior,NaN,NaN,...,NaN,"At Zynga, we bring people together through the...",Adzuna,5657839002,https://www.adzuna.es/details/5657839002?utm_m...,NaN,Página no encontrada - adzuna.es ¿Qué? ¿Dónde?...,None,True,"At Zynga, we bring people together through the..."

In [15]:

df_Adzuna_desc_edit = pd.merge(df_Adzuna, df_Adzuna_desc[["id", "descripcion_final", "es_truncada"]], on="id", how="left")
df_Adzuna_desc_edit

,titulo,empresa,ubicacion,contract_type,contract_time,descripcion,category,url,id,fecha,descripcion_final,es_truncada
0,Data Analyst,Perk,Barcelona,NaN,NaN,About Us Perk (formerly TravelPerk) is the int...,Unknown,https://www.adzuna.es/details/5655420542?utm_m...,5655420542,2026-03-05T22:17:29Z,About Us Perk (formerly TravelPerk) is the int...,False
1,Data Analyst,Veepee,Barcelona,NaN,NaN,Pioneer of online flash sales since 2001 and k...,Unknown,https://www.adzuna.es/details/5590818342?utm_m...,5590818342,2026-01-18T22:18:49Z,Pioneer of online flash sales since 2001 and k...,False
2,Data Analyst,Propelling Tech,Barcelona,NaN,NaN,"As a Data Analyst , you will be part of a high...",Unknown,https://www.adzuna.es/details/5584544401?utm_m...,5584544401,2026-01-14T20:09:21Z,"As a Data Analyst , you will be part of a high...",False
3,Data Analyst,PrimeIT,Barcelona,NaN,NaN,Qué buscamos? A partir de 3 años de experienci...,Unknown,https://www.adzuna.es/details/5304781614?utm_m...,5304781614,2025-07-16T00:10:07Z,Qué buscamos? A partir de 3 años de experienc...,False
4,Data Analyst Jr,Solicitud de empleo para Data Analyst Jr en DD...,Barcelona,NaN,NaN,"Perfil Si te apasionan los datos, quieres apre...",Unknown,https://www.adzuna.es/details/5556867176?utm_m...,5556867176,2025-12-26T20:51:02Z,"Perfil Si te apasionan los datos, quieres apre...",False
...,...,...,...,...,...,...,...,...,...,...,...,...
71,Senior Finance Systems Project Manager - HQ,Glovo,Barcelona,NaN,NaN,Job Description YOUR MISSION To be a Project M...,Unknown,https://www.adzuna.es/details/5648038417?utm_m...,5648038417,2026-02-28T01:45:31Z,Senior Finance Systems Project Manager - HQ Ub...,False
72,HQ BARCELONA - Senior Python Developer (Data T...,Jobandtalent,Barcelona,NaN,NaN,Who we are : We are a workforce on-demand comp...,Trabajos en informática,https://www.adzuna.es/details/4800600477?utm_m...,4800600477,2024-07-30T15:53:31Z,Who we are: We are a workforce on-demand compa...,False
73,Analista de Producto,Product Madness,Barcelona,NaN,NaN,Estamos ampliando nuestros equipos y esta es u...,Unknown,https://www.adzuna.es/details/5548465130?utm_m...,5548465130,2025-12-19T14:04:21Z,Estamos ampliando nuestros equipos y esta es u...,False
74,Senior Data Architect,Bunge,Barcelona,NaN,NaN,Location : Barcelona Hub City : Barcelona Stat...,Unknown,https://www.adzuna.es/details/5314694773?utm_m...,5314694773,2025-07-21T17:19:07Z,Location : Barcelona Hub City : Barcelona Stat...,False
75,Demand Generation Analyst (Temporary Contract),SAP,Barcelona,NaN,NaN,Demand Generation Analyst (Temporary Contract)...,Unknown,https://www.adzuna.es/details/5656541670?utm_m...,5656541670,2026-03-06T20:55:36Z,Demand Generation Analyst (Temporary Contract)...,True

In [16]:
# Exportar el DataFrame con la descripcion completa filtrada y los procesos realizados
df_Adzuna_desc.to_csv("df_Adzuna_descripcion_completa.csv", index=False)

In [17]:
# Exportar el DataFrame original con la descripcion final editada 
df_Adzuna_desc_edit.to_csv("df_Adzuna_descripcion_editada.csv", index=False)